In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
just_checking_integrity=False

In [ ]:
import gc
import pandas as pd
import scipy.sparse as sps

In [ ]:
valid=sps.load_npz("/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/processed_data/URM_valid_bought.npz")
bought=valid.indices

In [ ]:
dataset=None
dataset_max=None
#["UCF","ICBF","ICF","Graph","TopPop100","TopPop50","TopPop15"]
#for file in ["UCF","ICBF","Graph","ICF","UCF_W","ICBF_W","Graph_W","ICF_W","UCF_WW","ICBF_WW","Graph_WW","ICF_WW"]:
for file in ["UCF_W"]:
    print(gc.collect())
    print(f"loading {file}")
    df=pd.read_csv(f"/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/candidates/traditional_recs/train/{file}.csv")
    print(len(df))
    print(f"loaded {file}")
    for col in df:
        if "Max" in col:
            df_max=df[["Session_Id",col]].drop_duplicates()
        elif "Score" in col:
            df_feats=df[["Session_Id","Item_ID",col]]
    if dataset is None:
        dataset=df_feats
        dataset_max=df_max
    else:
        dataset=dataset.merge(df_feats,on=["Session_Id","Item_ID"],how="outer")
        dataset_max=dataset_max.merge(df_max,on=["Session_Id"],how="outer")
    del df


#del dataset_max
del df_feats
del df_max

0
loading UCF_W
18588455
loaded UCF_W

In [ ]:
import ast
submission_df=pd.read_csv("/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/candidates/NN/GRU/train/candidates.csv")
if just_checking_integrity:
    submission_df["score"]=submission_df["score"].apply(lambda x:x.replace("-inf","0")).apply(lambda x:x.replace("+inf","0")).apply(lambda x:x.replace("inf","0"))
    submission_df["score"]=submission_df["score"].map(ast.literal_eval)
else:
    submission_df["score"]=submission_df["score"].map(ast.literal_eval)
submission_df["code"]=submission_df["code"].map(ast.literal_eval)
submission_df["rank"]=submission_df["rank"].map(ast.literal_eval)
submission_df = submission_df.explode(['code','score', 'rank'])
submission_df[["session_id","code","rank"]]=submission_df[["session_id","code","rank"]].astype(int)
submission_df.rename(columns={"code":"Item_ID","session_id":"Session_Id","rank":"rank_gru","score":"score_gru"},inplace=True)

In [ ]:
submission_df.head()

   Session_Id  Item_ID score_gru  rank_gru
0      918382     3844  0.021967         1
0      918382     3678  0.016598         2
0      918382     1189  0.015711         3
0      918382      446   0.01126         4
0      918382     1813  0.009247         5

In [ ]:
# import ast
# submission_df_tr=pd.read_csv("/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/candidates/NN/Transformer/train/candidates.csv")
# if just_checking_integrity:
#     submission_df_tr["score"]=submission_df_tr["score"].apply(lambda x:x.replace("-inf","0"))
#     submission_df_tr["score"]=submission_df_tr["score"].map(ast.literal_eval)
# else:
#     submission_df_tr["score"]=submission_df_tr["score"].map(ast.literal_eval)
# submission_df_tr["code"]=submission_df_tr["code"].map(ast.literal_eval)
# submission_df_tr["rank"]=submission_df_tr["rank"].map(ast.literal_eval)
# submission_df_tr = submission_df_tr.explode(['code','score', 'rank'])
# submission_df_tr[["session_id","code","rank"]]=submission_df_tr[["session_id","code","rank"]].astype(int)
# submission_df_tr.rename(columns={"code":"Item_ID","session_id":"Session_Id","rank":"rank_transformer","score":"score_transformer"},inplace=True)

In [ ]:
# import ast
# submission_df_LSTM=pd.read_csv("/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/candidates/NN/LSTM/train/candidates.csv")
# if just_checking_integrity:
#     submission_df_LSTM["score"]=submission_df_LSTM["score"].apply(lambda x:x.replace("-inf","0"))
#     submission_df_LSTM["score"]=submission_df_LSTM["score"].map(ast.literal_eval)
# else:
#     submission_df_LSTM["score"]=submission_df_LSTM["score"].map(ast.literal_eval)
# submission_df_LSTM["code"]=submission_df_LSTM["code"].map(ast.literal_eval)
# submission_df_LSTM["rank"]=submission_df_LSTM["rank"].map(ast.literal_eval)
# submission_df_LSTM = submission_df_LSTM.explode(['code','score', 'rank'])
# submission_df_LSTM[["session_id","code","rank"]]=submission_df_LSTM[["session_id","code","rank"]].astype(int)
# submission_df_LSTM.rename(columns={"code":"Item_ID","session_id":"Session_Id","rank":"rank_LSTM","score":"score_LSTM"},inplace=True)

In [ ]:
dataset=dataset.merge(submission_df,on=["Session_Id","Item_ID"],how="outer")
#dataset=dataset.merge(submission_df_tr,on=["Session_Id","Item_ID"],how="outer")
#dataset=dataset.merge(submission_df_LSTM,on=["Session_Id","Item_ID"],how="outer")

dataset=dataset.merge(dataset_max,on=["Session_Id"],how="left")

In [ ]:
if just_checking_integrity:
    dataset=dataset[:int(0.5*len(dataset))]

In [ ]:
#del dataset_max
#del submission_df
#del submission_df_tr

In [ ]:
import numpy as np
sessions=np.unique(dataset["Session_Id"])
train=pd.DataFrame()
train["Session_Id"]=sessions
if just_checking_integrity:
    train["Item_ID"]=bought[:len(sessions)]
else:
    train["Item_ID"]=bought
train["target"]=1

In [ ]:
gc.collect()

209

In [ ]:
dataset=dataset.merge(train,on=["Session_Id","Item_ID"],how="left")
dataset.fillna(0,inplace=True)
gc.collect()

0

In [ ]:
dataset["target"]=dataset["target"].astype("int8")
gc.collect()

0

In [ ]:
sessions_containing_bought_among_candidates=dataset[["Session_Id","target"]].groupby("Session_Id").agg(sum).reset_index()
sessions_containing_bought_among_candidates=sessions_containing_bought_among_candidates.loc[sessions_containing_bought_among_candidates["target"]>0]

dataset=dataset[dataset['Session_Id'].isin(sessions_containing_bought_among_candidates["Session_Id"].tolist())]

In [ ]:
NHITS=len(dataset['Session_Id'].unique())
HITRATE=NHITS/81600 #approximate value
HITRATE

0.6025

In [ ]:
dataset.head(20)

,Session_Id,Item_ID,Score_UCF_W,score_gru,rank_gru,Max_Score_UCF_W,target
209,918383,55,0.054177,0.000000,0.0,594.02826,0
210,918383,122,0.025767,0.000000,0.0,594.02826,0
211,918383,189,0.129413,0.000446,76.0,594.02826,0
212,918383,215,0.036236,0.000000,0.0,594.02826,0
213,918383,260,0.039900,0.000000,0.0,594.02826,0
214,918383,320,0.040230,0.000786,42.0,594.02826,0
215,918383,357,0.040280,0.000000,0.0,594.02826,0
216,918383,379,0.046153,0.000000,0.0,594.02826,0
217,918383,421,0.064009,0.000369,91.0,594.02826,0
218,918383,506,0.032975,0.000000,0.0,594.02826,0
219,918383,548,0.230510,0.000676,50.0,594.02826,0
220,918383,554,0.029226,0.000000,0.0,594.02826,0
221,918383,609,0.052033,0.000000,0.0,594.02826,0
222,918383,676,0.090545,0.000477,70.0,594.02826,0
223,918383,786,0.261841,0.005555,9.0,594.02826,0
224,918383,815,0.083969,0.002622,19.0,594.02826,0
225,918383,851,0.138455,0.001152,28.0,594.02826,0
226,918383,933,0.079789,0.000488,68.0,594.02826,0
227,918383,943,0.030199,0.000000,0.0,594.02826,0
228,918383,965,0.033015,0.000000,0.0,594.02826,0

In [ ]:
dataset

,Session_Id,Item_ID,Score_UCF_W,score_gru,rank_gru,Max_Score_UCF_W,target
209,918383,55,0.054177,0.000000,0.0,594.028260,0
210,918383,122,0.025767,0.000000,0.0,594.028260,0
211,918383,189,0.129413,0.000446,76.0,594.028260,0
212,918383,215,0.036236,0.000000,0.0,594.028260,0
213,918383,260,0.039900,0.000000,0.0,594.028260,0
...,...,...,...,...,...,...,...
22882238,999998,4347,0.000000,0.000617,96.0,81.306076,0
22882239,999998,4587,0.000000,0.000617,97.0,81.306076,0
22882240,999998,1714,0.000000,0.000616,98.0,81.306076,0
22882241,999998,260,0.000000,0.000616,99.0,81.306076,0
22882242,999998,4061,0.000000,0.000605,100.0,81.306076,0

In [ ]:
dataset_macro_features = pd.read_csv('/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/processed_data/macro_feats_NN.csv',
                                     usecols=['session_id',
                                                'session_similarity',
                                                'session_similarity_uniques', 'session_similarity_feats', 'session_similarity_feats_uniques',
                                              'length_of_session_seconds',
                   'avg_time_spent_per_item_seconds',
                   'variance_time_spent_per_item_seconds',
                   'n_seen_items',
                   'n_unique_items',])

dataset_macro_features.rename(columns={'session_id':'Session_Id'}, inplace=True)
dataset = dataset.merge(dataset_macro_features, on='Session_Id', how='left')
del dataset_macro_features

In [ ]:
#dataset.drop('Max_Score_TopPop15', axis=1, inplace=True)

In [ ]:
from sklearn.model_selection import KFold
import lightgbm
import os
k=10


score=0
kf = KFold(n_splits=k)
index=0
for train_index, valid_index in kf.split(train):

    train_sessions=train["Session_Id"][train_index].tolist()
    valid_sessions=train["Session_Id"][valid_index].tolist()

    train_set=dataset[dataset["Session_Id"].isin(train_sessions)]
    valid_set=dataset[dataset["Session_Id"].isin(valid_sessions)]

    train_set=train_set.sort_values("Session_Id")
    valid_set=valid_set.sort_values("Session_Id")

    qids_train = train_set[["Session_Id"]].groupby("Session_Id")["Session_Id"].count().to_numpy()
    qids_valid = valid_set[["Session_Id"]].groupby("Session_Id")["Session_Id"].count().to_numpy()

    X_train=train_set.drop(["target","Session_Id","Item_ID"],axis=1)
    y_train=train_set["target"]

    X_valid=valid_set.drop(["target","Session_Id","Item_ID"],axis=1)
    y_valid=valid_set["target"]

    model = lightgbm.LGBMRanker(
    objective="lambdarank",
    #objective="rank_xendcg",
    #metric="mrr",
    # n_estimators=2000,
    n_estimators=100,
    lambdarank_truncation_level=103,
    reg_alpha=1e-4,
    learning_rate=0.05,
    min_child_samples=400,
    subsample=0.8,
    subsample_freq=20
    )
    ranker=model.fit(
        X=X_train,
        y=y_train,
        group=qids_train,
        eval_set=[(X_valid, y_valid)],
        eval_group=[qids_valid],
        eval_at=(100),
        callbacks=[lightgbm.log_evaluation(),lightgbm.early_stopping(20,first_metric_only=True)],
        #verbose=10,
        eval_metric=["map","ndcg"]
    )
    ranker.booster_.save_model(f'/content/drive/MyDrive/RS2024/Trial02/recsys2022/rankers/model_{index}.txt')
    #Get maximum val score
    score+=np.max(ranker._evals_result["valid_0"]["map@100"])
    index+=1

[LightGBM] [Info] Total groups: 43740, total data: 12216239
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.560352 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2798
[LightGBM] [Info] Number of data points in the train set: 12216239, number of used features: 13
[LightGBM] [Info] Total groups: 5424, total data: 1522006
[1]	valid_0's map@100: 0.225362	valid_0's ndcg@100: 0.351545
Training until validation scores don't improve for 20 rounds
[2]	valid_0's map@100: 0.255184	valid_0's ndcg@100: 0.374718
[3]	valid_0's map@100: 0.259942	valid_0's ndcg@100: 0.379164
[4]	valid_0's map@100: 0.259876	valid_0's ndcg@100: 0.379016
[5]	valid_0's map@100: 0.260764	valid_0's ndcg@100: 0.379822
[6]	valid_0's map@100: 0.260681	valid_0's ndcg@100: 0.379682
[7]	valid_0's map@100: 0.261224	valid_0's ndcg@100: 0.380157
[8]	valid_0's map@100: 0.261183	valid_0's ndcg@100: 0.380245
[9]	valid_0's map@100: 0.261791	valid_0's ndcg@100: 0.380765
[10]	valid_0's map@100: 0.261461	valid_0's ndcg@100: 0.380598
[11]	valid_0's map@100: 0.260986	valid_0's ndcg@100: 0.38034
[12]	valid_0's map@100: 0.261407	valid_0's ndcg@100: 0.380538
[13]	valid_0's map@100: 0.261058	valid_0's ndcg@100: 0.380278
[14]	valid_0's map@100: 0.262028	valid_0's ndcg@100: 0.380943
[15]	valid_0's map@100: 0.262091	valid_0's ndcg@100: 0.381112
[16]	valid_0's map@100: 0.262549	valid_0's ndcg@100: 0.381489
[17]	valid_0's map@100: 0.261818	valid_0's ndcg@100: 0.381084
[18]	valid_0's map@100: 0.26204	valid_0's ndcg@100: 0.381194
[19]	valid_0's map@100: 0.262544	valid_0's ndcg@100: 0.381489
[20]	valid_0's map@100: 0.262166	valid_0's ndcg@100: 0.38138
[21]	valid_0's map@100: 0.262124	valid_0's ndcg@100: 0.381337
[22]	valid_0's map@100: 0.262421	valid_0's ndcg@100: 0.381378
[23]	valid_0's map@100: 0.262053	valid_0's ndcg@100: 0.381101
[24]	valid_0's map@100: 0.261595	valid_0's ndcg@100: 0.381
[25]	valid_0's map@100: 0.261585	valid_0's ndcg@100: 0.380881
[26]	valid_0's map@100: 0.261374	valid_0's ndcg@100: 0.380766
[27]	valid_0's map@100: 0.260807	valid_0's ndcg@100: 0.380337
[28]	valid_0's map@100: 0.26115	valid_0's ndcg@100: 0.380493
[29]	valid_0's map@100: 0.260626	valid_0's ndcg@100: 0.380103
[30]	valid_0's map@100: 0.260892	valid_0's ndcg@100: 0.380391
[31]	valid_0's map@100: 0.260273	valid_0's ndcg@100: 0.38002
[32]	valid_0's map@100: 0.260671	valid_0's ndcg@100: 0.380212
[33]	valid_0's map@100: 0.260407	valid_0's ndcg@100: 0.380112
[34]	valid_0's map@100: 0.260592	valid_0's ndcg@100: 0.380195
[35]	valid_0's map@100: 0.260374	valid_0's ndcg@100: 0.380052
[36]	valid_0's map@100: 0.260128	valid_0's ndcg@100: 0.379958
Early stopping, best iteration is:
[16]	valid_0's map@100: 0.262549	valid_0's ndcg@100: 0.381489
Evaluated only: map@100
[LightGBM] [Info] Total groups: 43869, total data: 12259533
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.472815 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2797
[LightGBM] [Info] Number of data points in the train set: 12259533, number of used features: 13
[LightGBM] [Info] Total groups: 5295, total data: 1478712
[1]	valid_0's map@100: 0.237728	valid_0's ndcg@100: 0.364347
Training until validation scores don't improve for 20 rounds
[2]	valid_0's map@100: 0.268575	valid_0's ndcg@100: 0.389001
[3]	valid_0's map@100: 0.272115	valid_0's ndcg@100: 0.391653
[4]	valid_0's map@100: 0.274004	valid_0's ndcg@100: 0.392977
[5]	valid_0's map@100: 0.274366	valid_0's ndcg@100: 0.393686
[6]	valid_0's map@100: 0.275036	valid_0's ndcg@100: 0.394421
[7]	valid_0's map@100: 0.274701	valid_0's ndcg@100: 0.394267
[8]	valid_0's map@100: 0.275977	valid_0's ndcg@100: 0.395235
[9]	valid_0's map@100: 0.276193	valid_0's ndcg@100: 0.395395
[10]	valid_0's map@100: 0.276115	valid_0's ndcg@100: 0.395363
[11]	valid_0's map@100: 0.276225	valid_0's ndcg@100: 0.395497
[12]	valid_0's map@100: 0.276292	valid_0's ndcg@100: 0.395423
[13]	valid_0's map@100: 0.276523	valid_0's ndcg@100: 0.395812
[14]	valid_0's map@100: 0.276325	valid_0's ndcg@100: 0.395568
[15]	valid_0's map@100: 0.276195	valid_0's ndcg@100: 0.395551
[16]	valid_0's map@100: 0.276518	valid_0's ndcg@100: 0.39579
[17]	valid_0's map@100: 0.276337	valid_0's ndcg@100: 0.39568
[18]	valid_0's map@100: 0.276693	valid_0's ndcg@100: 0.395934
[19]	valid_0's map@100: 0.276557	valid_0's ndcg@100: 0.395779
[20]	valid_0's map@100: 0.276133	valid_0's ndcg@100: 0.395492
[21]	valid_0's map@100: 0.276836	valid_0's ndcg@100: 0.396064
[22]	valid_0's map@100: 0.276568	valid_0's ndcg@100: 0.395911
[23]	valid_0's map@100: 0.276506	valid_0's ndcg@100: 0.395942
[24]	valid_0's map@100: 0.276385	valid_0's ndcg@100: 0.395791
[25]	valid_0's map@100: 0.276647	valid_0's ndcg@100: 0.396006
[26]	valid_0's map@100: 0.276908	valid_0's ndcg@100: 0.39618
[27]	valid_0's map@100: 0.276801	valid_0's ndcg@100: 0.39608
[28]	valid_0's map@100: 0.276597	valid_0's ndcg@100: 0.395955
[29]	valid_0's map@100: 0.276683	valid_0's ndcg@100: 0.396009
[30]	valid_0's map@100: 0.277054	valid_0's ndcg@100: 0.396249
[31]	valid_0's map@100: 0.27731	valid_0's ndcg@100: 0.396558
[32]	valid_0's map@100: 0.277098	valid_0's ndcg@100: 0.39632
[33]	valid_0's map@100: 0.276902	valid_0's ndcg@100: 0.396191
[34]	valid_0's map@100: 0.277102	valid_0's ndcg@100: 0.396328
[35]	valid_0's map@100: 0.277331	valid_0's ndcg@100: 0.39653
[36]	valid_0's map@100: 0.27724	valid_0's ndcg@100: 0.396474
[37]	valid_0's map@100: 0.277608	valid_0's ndcg@100: 0.396746
[38]	valid_0's map@100: 0.277225	valid_0's ndcg@100: 0.39643
[39]	valid_0's map@100: 0.277699	valid_0's ndcg@100: 0.396881
[40]	valid_0's map@100: 0.277166	valid_0's ndcg@100: 0.39644
[41]	valid_0's map@100: 0.277333	valid_0's ndcg@100: 0.396589
[42]	valid_0's map@100: 0.277891	valid_0's ndcg@100: 0.397095
[43]	valid_0's map@100: 0.277561	valid_0's ndcg@100: 0.396851
[44]	valid_0's map@100: 0.277835	valid_0's ndcg@100: 0.397061
[45]	valid_0's map@100: 0.278168	valid_0's ndcg@100: 0.397324
[46]	valid_0's map@100: 0.278475	valid_0's ndcg@100: 0.397556
[47]	valid_0's map@100: 0.278599	valid_0's ndcg@100: 0.397624
[48]	valid_0's map@100: 0.278656	valid_0's ndcg@100: 0.397667
[49]	valid_0's map@100: 0.27866	valid_0's ndcg@100: 0.397653
[50]	valid_0's map@100: 0.278821	valid_0's ndcg@100: 0.397863
[51]	valid_0's map@100: 0.278876	valid_0's ndcg@100: 0.397966
[52]	valid_0's map@100: 0.278899	valid_0's ndcg@100: 0.397985
[53]	valid_0's map@100: 0.278791	valid_0's ndcg@100: 0.397998
[54]	valid_0's map@100: 0.278922	valid_0's ndcg@100: 0.398123
[55]	valid_0's map@100: 0.279001	valid_0's ndcg@100: 0.39822
[56]	valid_0's map@100: 0.279132	valid_0's ndcg@100: 0.398301
[57]	valid_0's map@100: 0.278921	valid_0's ndcg@100: 0.398232
[58]	valid_0's map@100: 0.278595	valid_0's ndcg@100: 0.397965
[59]	valid_0's map@100: 0.278774	valid_0's ndcg@100: 0.398072
[60]	valid_0's map@100: 0.278951	valid_0's ndcg@100: 0.398231
[61]	valid_0's map@100: 0.278589	valid_0's ndcg@100: 0.397978
[62]	valid_0's map@100: 0.278473	valid_0's ndcg@100: 0.397805
[63]	valid_0's map@100: 0.278252	valid_0's ndcg@100: 0.397746
[64]	valid_0's map@100: 0.278185	valid_0's ndcg@100: 0.397736
[65]	valid_0's map@100: 0.278167	valid_0's ndcg@100: 0.397732
[66]	valid_0's map@100: 0.278158	valid_0's ndcg@100: 0.397717
[67]	valid_0's map@100: 0.278111	valid_0's ndcg@100: 0.3976
[68]	valid_0's map@100: 0.277934	valid_0's ndcg@100: 0.397433
[69]	valid_0's map@100: 0.277967	valid_0's ndcg@100: 0.39746
[70]	valid_0's map@100: 0.277986	valid_0's ndcg@100: 0.397447
[71]	valid_0's map@100: 0.278169	valid_0's ndcg@100: 0.397534
[72]	valid_0's map@100: 0.277883	valid_0's ndcg@100: 0.397286
[73]	valid_0's map@100: 0.278055	valid_0's ndcg@100: 0.39739
[74]	valid_0's map@100: 0.278026	valid_0's ndcg@100: 0.397368
[75]	valid_0's map@100: 0.277949	valid_0's ndcg@100: 0.39731
[76]	valid_0's map@100: 0.277682	valid_0's ndcg@100: 0.397114
Early stopping, best iteration is:
[56]	valid_0's map@100: 0.279132	valid_0's ndcg@100: 0.398301
Evaluated only: map@100
[LightGBM] [Info] Total groups: 44204, total data: 12351726
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.588047 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2800
[LightGBM] [Info] Number of data points in the train set: 12351726, number of used features: 13
[LightGBM] [Info] Total groups: 4960, total data: 1386519
[1]	valid_0's map@100: 0.219255	valid_0's ndcg@100: 0.346355
Training until validation scores don't improve for 20 rounds
[2]	valid_0's map@100: 0.257415	valid_0's ndcg@100: 0.376621
[3]	valid_0's map@100: 0.262595	valid_0's ndcg@100: 0.380444
[4]	valid_0's map@100: 0.264676	valid_0's ndcg@100: 0.382508
[5]	valid_0's map@100: 0.264902	valid_0's ndcg@100: 0.382241
[6]	valid_0's map@100: 0.265177	valid_0's ndcg@100: 0.382609
[7]	valid_0's map@100: 0.264748	valid_0's ndcg@100: 0.382222
[8]	valid_0's map@100: 0.264643	valid_0's ndcg@100: 0.382155
[9]	valid_0's map@100: 0.265252	valid_0's ndcg@100: 0.382713
[10]	valid_0's map@100: 0.265584	valid_0's ndcg@100: 0.383106
[11]	valid_0's map@100: 0.265365	valid_0's ndcg@100: 0.382948
[12]	valid_0's map@100: 0.266562	valid_0's ndcg@100: 0.383855
[13]	valid_0's map@100: 0.266055	valid_0's ndcg@100: 0.383545
[14]	valid_0's map@100: 0.265957	valid_0's ndcg@100: 0.383667
[15]	valid_0's map@100: 0.266014	valid_0's ndcg@100: 0.383536
[16]	valid_0's map@100: 0.266202	valid_0's ndcg@100: 0.383722
[17]	valid_0's map@100: 0.265843	valid_0's ndcg@100: 0.383412
[18]	valid_0's map@100: 0.266301	valid_0's ndcg@100: 0.383879
[19]	valid_0's map@100: 0.26576	valid_0's ndcg@100: 0.383563
[20]	valid_0's map@100: 0.265633	valid_0's ndcg@100: 0.383547
[21]	valid_0's map@100: 0.265517	valid_0's ndcg@100: 0.383416
[22]	valid_0's map@100: 0.265628	valid_0's ndcg@100: 0.383421
[23]	valid_0's map@100: 0.265848	valid_0's ndcg@100: 0.383705
[24]	valid_0's map@100: 0.265624	valid_0's ndcg@100: 0.383505
[25]	valid_0's map@100: 0.265883	valid_0's ndcg@100: 0.383694
[26]	valid_0's map@100: 0.265673	valid_0's ndcg@100: 0.383668
[27]	valid_0's map@100: 0.266309	valid_0's ndcg@100: 0.384002
[28]	valid_0's map@100: 0.266387	valid_0's ndcg@100: 0.384092
[29]	valid_0's map@100: 0.266472	valid_0's ndcg@100: 0.384161
[30]	valid_0's map@100: 0.266527	valid_0's ndcg@100: 0.384236
[31]	valid_0's map@100: 0.266659	valid_0's ndcg@100: 0.384303
[32]	valid_0's map@100: 0.267031	valid_0's ndcg@100: 0.384519
[33]	valid_0's map@100: 0.267107	valid_0's ndcg@100: 0.384556
[34]	valid_0's map@100: 0.266907	valid_0's ndcg@100: 0.384573
[35]	valid_0's map@100: 0.266846	valid_0's ndcg@100: 0.384461
[36]	valid_0's map@100: 0.26668	valid_0's ndcg@100: 0.384348
[37]	valid_0's map@100: 0.266771	valid_0's ndcg@100: 0.384459
[38]	valid_0's map@100: 0.267014	valid_0's ndcg@100: 0.384632
[39]	valid_0's map@100: 0.267082	valid_0's ndcg@100: 0.384723
[40]	valid_0's map@100: 0.266704	valid_0's ndcg@100: 0.3845
[41]	valid_0's map@100: 0.266817	valid_0's ndcg@100: 0.384577
[42]	valid_0's map@100: 0.266588	valid_0's ndcg@100: 0.38449
[43]	valid_0's map@100: 0.266633	valid_0's ndcg@100: 0.384468
[44]	valid_0's map@100: 0.266649	valid_0's ndcg@100: 0.384477
[45]	valid_0's map@100: 0.266761	valid_0's ndcg@100: 0.384596
[46]	valid_0's map@100: 0.266887	valid_0's ndcg@100: 0.384747
[47]	valid_0's map@100: 0.266373	valid_0's ndcg@100: 0.384343
[48]	valid_0's map@100: 0.266452	valid_0's ndcg@100: 0.384301
[49]	valid_0's map@100: 0.266562	valid_0's ndcg@100: 0.384323
[50]	valid_0's map@100: 0.266137	valid_0's ndcg@100: 0.384029
[51]	valid_0's map@100: 0.266355	valid_0's ndcg@100: 0.384077
[52]	valid_0's map@100: 0.265674	valid_0's ndcg@100: 0.383576
[53]	valid_0's map@100: 0.266185	valid_0's ndcg@100: 0.38404
Early stopping, best iteration is:
[33]	valid_0's map@100: 0.267107	valid_0's ndcg@100: 0.384556
Evaluated only: map@100
[LightGBM] [Info] Total groups: 44113, total data: 12322514
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.684551 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2796
[LightGBM] [Info] Number of data points in the train set: 12322514, number of used features: 13
[LightGBM] [Info] Total groups: 5051, total data: 1415731
[1]	valid_0's map@100: 0.254452	valid_0's ndcg@100: 0.378516
Training until validation scores don't improve for 20 rounds
[2]	valid_0's map@100: 0.291837	valid_0's ndcg@100: 0.40816
[3]	valid_0's map@100: 0.292953	valid_0's ndcg@100: 0.40952
[4]	valid_0's map@100: 0.297809	valid_0's ndcg@100: 0.41308
[5]	valid_0's map@100: 0.295773	valid_0's ndcg@100: 0.411744
[6]	valid_0's map@100: 0.296943	valid_0's ndcg@100: 0.412415
[7]	valid_0's map@100: 0.297159	valid_0's ndcg@100: 0.412381
[8]	valid_0's map@100: 0.294666	valid_0's ndcg@100: 0.410551
[9]	valid_0's map@100: 0.294966	valid_0's ndcg@100: 0.410814
[10]	valid_0's map@100: 0.297199	valid_0's ndcg@100: 0.412428
[11]	valid_0's map@100: 0.295394	valid_0's ndcg@100: 0.411118
[12]	valid_0's map@100: 0.296587	valid_0's ndcg@100: 0.412009
[13]	valid_0's map@100: 0.2961	valid_0's ndcg@100: 0.411711
[14]	valid_0's map@100: 0.29739	valid_0's ndcg@100: 0.41279
[15]	valid_0's map@100: 0.296108	valid_0's ndcg@100: 0.411856
[16]	valid_0's map@100: 0.296261	valid_0's ndcg@100: 0.412028
[17]	valid_0's map@100: 0.296579	valid_0's ndcg@100: 0.412149
[18]	valid_0's map@100: 0.297283	valid_0's ndcg@100: 0.412627
[19]	valid_0's map@100: 0.296523	valid_0's ndcg@100: 0.412079
[20]	valid_0's map@100: 0.296889	valid_0's ndcg@100: 0.412362
[21]	valid_0's map@100: 0.297083	valid_0's ndcg@100: 0.412683
[22]	valid_0's map@100: 0.297094	valid_0's ndcg@100: 0.412638
[23]	valid_0's map@100: 0.297425	valid_0's ndcg@100: 0.412911
[24]	valid_0's map@100: 0.297247	valid_0's ndcg@100: 0.412876
Early stopping, best iteration is:
[4]	valid_0's map@100: 0.297809	valid_0's ndcg@100: 0.41308
Evaluated only: map@100
[LightGBM] [Info] Total groups: 44219, total data: 12342533
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.551332 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2795
[LightGBM] [Info] Number of data points in the train set: 12342533, number of used features: 13
[LightGBM] [Info] Total groups: 4945, total data: 1395712
[1]	valid_0's map@100: 0.253804	valid_0's ndcg@100: 0.377929
Training until validation scores don't improve for 20 rounds
[2]	valid_0's map@100: 0.296058	valid_0's ndcg@100: 0.411027
[3]	valid_0's map@100: 0.297413	valid_0's ndcg@100: 0.412235
[4]	valid_0's map@100: 0.29876	valid_0's ndcg@100: 0.413419
[5]	valid_0's map@100: 0.29926	valid_0's ndcg@100: 0.414016
[6]	valid_0's map@100: 0.300284	valid_0's ndcg@100: 0.414779
[7]	valid_0's map@100: 0.300163	valid_0's ndcg@100: 0.414718
[8]	valid_0's map@100: 0.298075	valid_0's ndcg@100: 0.413268
[9]	valid_0's map@100: 0.299958	valid_0's ndcg@100: 0.414629
[10]	valid_0's map@100: 0.300787	valid_0's ndcg@100: 0.415421
[11]	valid_0's map@100: 0.300845	valid_0's ndcg@100: 0.415445
[12]	valid_0's map@100: 0.301116	valid_0's ndcg@100: 0.415704
[13]	valid_0's map@100: 0.301434	valid_0's ndcg@100: 0.415979
[14]	valid_0's map@100: 0.301443	valid_0's ndcg@100: 0.415928
[15]	valid_0's map@100: 0.300688	valid_0's ndcg@100: 0.415246
[16]	valid_0's map@100: 0.301275	valid_0's ndcg@100: 0.415679
[17]	valid_0's map@100: 0.301164	valid_0's ndcg@100: 0.415506
[18]	valid_0's map@100: 0.301694	valid_0's ndcg@100: 0.416038
[19]	valid_0's map@100: 0.300302	valid_0's ndcg@100: 0.415086
[20]	valid_0's map@100: 0.301766	valid_0's ndcg@100: 0.416075
[21]	valid_0's map@100: 0.301283	valid_0's ndcg@100: 0.415718
[22]	valid_0's map@100: 0.300545	valid_0's ndcg@100: 0.41508
[23]	valid_0's map@100: 0.300262	valid_0's ndcg@100: 0.414842
[24]	valid_0's map@100: 0.300419	valid_0's ndcg@100: 0.414925
[25]	valid_0's map@100: 0.300197	valid_0's ndcg@100: 0.414861
[26]	valid_0's map@100: 0.299978	valid_0's ndcg@100: 0.414685
[27]	valid_0's map@100: 0.300029	valid_0's ndcg@100: 0.4147
[28]	valid_0's map@100: 0.299622	valid_0's ndcg@100: 0.414462
[29]	valid_0's map@100: 0.299811	valid_0's ndcg@100: 0.414608
[30]	valid_0's map@100: 0.299841	valid_0's ndcg@100: 0.414635
[31]	valid_0's map@100: 0.299734	valid_0's ndcg@100: 0.414581
[32]	valid_0's map@100: 0.300022	valid_0's ndcg@100: 0.414801
[33]	valid_0's map@100: 0.300031	valid_0's ndcg@100: 0.414871
[34]	valid_0's map@100: 0.300063	valid_0's ndcg@100: 0.414861
[35]	valid_0's map@100: 0.300205	valid_0's ndcg@100: 0.41499
[36]	valid_0's map@100: 0.300233	valid_0's ndcg@100: 0.41505
[37]	valid_0's map@100: 0.300465	valid_0's ndcg@100: 0.415262
[38]	valid_0's map@100: 0.300602	valid_0's ndcg@100: 0.415378
[39]	valid_0's map@100: 0.300705	valid_0's ndcg@100: 0.415469
[40]	valid_0's map@100: 0.30101	valid_0's ndcg@100: 0.415601
Early stopping, best iteration is:
[20]	valid_0's map@100: 0.301766	valid_0's ndcg@100: 0.416075
Evaluated only: map@100
[LightGBM] [Info] Total groups: 44154, total data: 12335401
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.512787 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2798
[LightGBM] [Info] Number of data points in the train set: 12335401, number of used features: 13
[LightGBM] [Info] Total groups: 5010, total data: 1402844
[1]	valid_0's map@100: 0.254518	valid_0's ndcg@100: 0.38018
Training until validation scores don't improve for 20 rounds
[2]	valid_0's map@100: 0.295236	valid_0's ndcg@100: 0.412003
[3]	valid_0's map@100: 0.295304	valid_0's ndcg@100: 0.412746
[4]	valid_0's map@100: 0.297934	valid_0's ndcg@100: 0.414963
[5]	valid_0's map@100: 0.299148	valid_0's ndcg@100: 0.415761
[6]	valid_0's map@100: 0.300405	valid_0's ndcg@100: 0.416934
[7]	valid_0's map@100: 0.300714	valid_0's ndcg@100: 0.417248
[8]	valid_0's map@100: 0.301184	valid_0's ndcg@100: 0.417674
[9]	valid_0's map@100: 0.301636	valid_0's ndcg@100: 0.418072
[10]	valid_0's map@100: 0.301526	valid_0's ndcg@100: 0.418
[11]	valid_0's map@100: 0.301555	valid_0's ndcg@100: 0.41831
[12]	valid_0's map@100: 0.301114	valid_0's ndcg@100: 0.417891
[13]	valid_0's map@100: 0.303094	valid_0's ndcg@100: 0.419343
[14]	valid_0's map@100: 0.302067	valid_0's ndcg@100: 0.418634
[15]	valid_0's map@100: 0.302134	valid_0's ndcg@100: 0.418658
[16]	valid_0's map@100: 0.302944	valid_0's ndcg@100: 0.41922
[17]	valid_0's map@100: 0.30182	valid_0's ndcg@100: 0.418355
[18]	valid_0's map@100: 0.302652	valid_0's ndcg@100: 0.418981
[19]	valid_0's map@100: 0.302248	valid_0's ndcg@100: 0.418647
[20]	valid_0's map@100: 0.302866	valid_0's ndcg@100: 0.41922
[21]	valid_0's map@100: 0.303756	valid_0's ndcg@100: 0.419909
[22]	valid_0's map@100: 0.303027	valid_0's ndcg@100: 0.419406
[23]	valid_0's map@100: 0.303277	valid_0's ndcg@100: 0.419599
[24]	valid_0's map@100: 0.30358	valid_0's ndcg@100: 0.419881
[25]	valid_0's map@100: 0.303352	valid_0's ndcg@100: 0.419665
[26]	valid_0's map@100: 0.304446	valid_0's ndcg@100: 0.420498
[27]	valid_0's map@100: 0.30445	valid_0's ndcg@100: 0.420482
[28]	valid_0's map@100: 0.304567	valid_0's ndcg@100: 0.42063
[29]	valid_0's map@100: 0.304985	valid_0's ndcg@100: 0.421081
[30]	valid_0's map@100: 0.305296	valid_0's ndcg@100: 0.421326
[31]	valid_0's map@100: 0.305142	valid_0's ndcg@100: 0.421288
[32]	valid_0's map@100: 0.304638	valid_0's ndcg@100: 0.42088
[33]	valid_0's map@100: 0.304945	valid_0's ndcg@100: 0.421137

In [ ]:
final_performcance=score/k
print("overall MAP@100 = ", final_performcance)

overall MAP@100 =  0.28914821284175457

In [ ]:
print("normalized score ", final_performcance*HITRATE)

normalized score  0.17421179823715713