In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
just_checking_integrity=False

In [ ]:
import gc
import pandas as pd
import scipy.sparse as sps

In [ ]:
valid=sps.load_npz("/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/processed_data/URM_valid_bought.npz")
bought=valid.indices

In [ ]:
dataset=None
dataset_max=None
#["UCF","ICBF","ICF","Graph","TopPop100","TopPop50","TopPop15"]
#for file in ["UCF","ICBF","Graph","ICF","UCF_W","ICBF_W","Graph_W","ICF_W","UCF_WW","ICBF_WW","Graph_WW","ICF_WW"]:
for file in ["UCF_W","ICBF_W","Graph_W","ICF_W"]:
    print(gc.collect())
    print(f"loading {file}")
    df=pd.read_csv(f"/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/candidates/traditional_recs/train/{file}.csv")
    print(len(df))
    print(f"loaded {file}")
    for col in df:
        if "Max" in col:
            df_max=df[["Session_Id",col]].drop_duplicates()
        elif "Score" in col:
            df_feats=df[["Session_Id","Item_ID",col]]
    if dataset is None:
        dataset=df_feats
        dataset_max=df_max
    else:
        dataset=dataset.merge(df_feats,on=["Session_Id","Item_ID"],how="outer")
        dataset_max=dataset_max.merge(df_max,on=["Session_Id"],how="outer")
    del df


del dataset_max
del df_feats
del df_max

0
loading UCF_W
18588455
loaded UCF_W
0
loading ICBF_W
16931962
loaded ICBF_W
0
loading Graph_W
9381571
loaded Graph_W
0
loading ICF_W
20341641
loaded ICF_W

In [ ]:
total_sessions = len(dataset['Session_Id'].unique())
print("Total sessions:", total_sessions)

Total sessions: 81618

In [ ]:
dataset

,Session_Id,Item_ID,Score_UCF_W,Score_ICBF_W,Score_Graph_W,Score_ICF_W
0,918382,78,0.515642,NaN,0.377850,0.587459
1,918382,178,0.281229,NaN,0.142546,0.412063
2,918382,230,0.127506,NaN,0.055109,0.022295
3,918382,242,0.395681,0.775898,0.273503,0.514097
4,918382,292,0.200113,0.601746,0.105606,0.458708
...,...,...,...,...,...,...
35891117,999999,14138,NaN,NaN,NaN,0.505847
35891118,999999,16357,NaN,NaN,NaN,0.005289
35891119,999999,16479,NaN,NaN,NaN,0.541090
35891120,999999,16520,NaN,NaN,NaN,0.359696
35891121,999999,18399,NaN,NaN,NaN,0.549199

In [ ]:
import ast
submission_df=pd.read_csv("/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/candidates/NN/GRU/train/candidates.csv")
if just_checking_integrity:
    submission_df["score"]=submission_df["score"].apply(lambda x:x.replace("-inf","0")).apply(lambda x:x.replace("+inf","0")).apply(lambda x:x.replace("inf","0"))
    submission_df["score"]=submission_df["score"].map(ast.literal_eval)
else:
    submission_df["score"]=submission_df["score"].map(ast.literal_eval)
submission_df["code"]=submission_df["code"].map(ast.literal_eval)
submission_df["rank"]=submission_df["rank"].map(ast.literal_eval)
submission_df = submission_df.explode(['code','score', 'rank'])
submission_df[["session_id","code","rank"]]=submission_df[["session_id","code","rank"]].astype(int)
submission_df.rename(columns={"code":"Item_ID","session_id":"Session_Id","rank":"rank_gru","score":"score_gru"},inplace=True)

In [ ]:
submission_df.head()

   Session_Id  Item_ID score_gru  rank_gru
0      918382     3844  0.021967         1
0      918382     3678  0.016598         2
0      918382     1189  0.015711         3
0      918382      446   0.01126         4
0      918382     1813  0.009247         5

In [ ]:
# import ast
# submission_df_tr=pd.read_csv("/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/candidates/NN/Transformer/train/candidates.csv")
# if just_checking_integrity:
#     submission_df_tr["score"]=submission_df_tr["score"].apply(lambda x:x.replace("-inf","0"))
#     submission_df_tr["score"]=submission_df_tr["score"].map(ast.literal_eval)
# else:
#     submission_df_tr["score"]=submission_df_tr["score"].map(ast.literal_eval)
# submission_df_tr["code"]=submission_df_tr["code"].map(ast.literal_eval)
# submission_df_tr["rank"]=submission_df_tr["rank"].map(ast.literal_eval)
# submission_df_tr = submission_df_tr.explode(['code','score', 'rank'])
# submission_df_tr[["session_id","code","rank"]]=submission_df_tr[["session_id","code","rank"]].astype(int)
# submission_df_tr.rename(columns={"code":"Item_ID","session_id":"Session_Id","rank":"rank_transformer","score":"score_transformer"},inplace=True)

In [ ]:
# import ast
# submission_df_LSTM=pd.read_csv("/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/candidates/NN/LSTM/train/candidates.csv")
# if just_checking_integrity:
#     submission_df_LSTM["score"]=submission_df_LSTM["score"].apply(lambda x:x.replace("-inf","0"))
#     submission_df_LSTM["score"]=submission_df_LSTM["score"].map(ast.literal_eval)
# else:
#     submission_df_LSTM["score"]=submission_df_LSTM["score"].map(ast.literal_eval)
# submission_df_LSTM["code"]=submission_df_LSTM["code"].map(ast.literal_eval)
# submission_df_LSTM["rank"]=submission_df_LSTM["rank"].map(ast.literal_eval)
# submission_df_LSTM = submission_df_LSTM.explode(['code','score', 'rank'])
# submission_df_LSTM[["session_id","code","rank"]]=submission_df_LSTM[["session_id","code","rank"]].astype(int)
# submission_df_LSTM.rename(columns={"code":"Item_ID","session_id":"Session_Id","rank":"rank_LSTM","score":"score_LSTM"},inplace=True)

In [ ]:
dataset=dataset.merge(submission_df,on=["Session_Id","Item_ID"],how="outer")
#dataset=dataset.merge(submission_df_tr,on=["Session_Id","Item_ID"],how="outer")
#dataset=dataset.merge(submission_df_LSTM,on=["Session_Id","Item_ID"],how="outer")

# dataset=dataset.merge(dataset_max,on=["Session_Id"],how="left")

In [ ]:
dataset

,Session_Id,Item_ID,Score_UCF_W,Score_ICBF_W,Score_Graph_W,Score_ICF_W,score_gru,rank_gru
0,918382,78,0.515642,NaN,0.377850,0.587459,NaN,NaN
1,918382,178,0.281229,NaN,0.142546,0.412063,NaN,NaN
2,918382,230,0.127506,NaN,0.055109,0.022295,NaN,NaN
3,918382,242,0.395681,0.775898,0.273503,0.514097,0.003217,14.0
4,918382,292,0.200113,0.601746,0.105606,0.458708,NaN,NaN
...,...,...,...,...,...,...,...,...
39064205,999999,2019,NaN,NaN,NaN,NaN,0.000588,92.0
39064206,999999,2316,NaN,NaN,NaN,NaN,0.000588,93.0
39064207,999999,3320,NaN,NaN,NaN,NaN,0.000578,96.0
39064208,999999,968,NaN,NaN,NaN,NaN,0.000561,99.0
39064209,999999,2186,NaN,NaN,NaN,NaN,0.000556,100.0

In [ ]:
if just_checking_integrity:
    dataset=dataset[:int(0.5*len(dataset))]

In [ ]:
# del dataset_max
del submission_df

In [ ]:
import numpy as np
sessions=np.unique(dataset["Session_Id"])
train=pd.DataFrame()
train["Session_Id"]=sessions
if just_checking_integrity:
    train["Item_ID"]=bought[:len(sessions)]
else:
    train["Item_ID"]=bought
train["target"]=1

In [ ]:
gc.collect()

242

In [ ]:
dataset=dataset.merge(train,on=["Session_Id","Item_ID"],how="left")
dataset.fillna(0,inplace=True)
gc.collect()

0

In [ ]:
dataset["target"]=dataset["target"].astype("int8")
gc.collect()

0

In [ ]:
sessions_containing_bought_among_candidates=dataset[["Session_Id","target"]].groupby("Session_Id").agg(sum).reset_index()
sessions_containing_bought_among_candidates=sessions_containing_bought_among_candidates.loc[sessions_containing_bought_among_candidates["target"]>0]

dataset=dataset[dataset['Session_Id'].isin(sessions_containing_bought_among_candidates["Session_Id"].tolist())]

In [ ]:
NHITS=len(dataset['Session_Id'].unique())
HITRATE=NHITS/81600
HITRATE

0.7326470588235294

In [ ]:
dataset

,Session_Id,Item_ID,Score_UCF_W,Score_ICBF_W,Score_Graph_W,Score_ICF_W,score_gru,rank_gru,target
209,918383,55,0.054177,0.632362,0.005355,0.018442,0.000000,0.0,0
210,918383,122,0.025767,0.000000,0.000000,0.000000,0.000000,0.0,0
211,918383,189,0.129413,0.000000,0.020602,0.278846,0.000446,76.0,0
212,918383,215,0.036236,0.000000,0.000000,0.000000,0.000000,0.0,0
213,918383,260,0.039900,0.000000,0.003595,0.012055,0.000000,0.0,0
...,...,...,...,...,...,...,...,...,...
39064205,999999,2019,0.000000,0.000000,0.000000,0.000000,0.000588,92.0,0
39064206,999999,2316,0.000000,0.000000,0.000000,0.000000,0.000588,93.0,0
39064207,999999,3320,0.000000,0.000000,0.000000,0.000000,0.000578,96.0,0
39064208,999999,968,0.000000,0.000000,0.000000,0.000000,0.000561,99.0,0
39064209,999999,2186,0.000000,0.000000,0.000000,0.000000,0.000556,100.0,0

In [ ]:
dataset_macro_features = pd.read_csv('/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/processed_data/macro_feats_NN.csv',
                                     usecols=['session_id',
                                                'session_similarity',
                                                'session_similarity_uniques', 'session_similarity_feats', 'session_similarity_feats_uniques',
                                              'length_of_session_seconds',
                   'avg_time_spent_per_item_seconds',
                   'variance_time_spent_per_item_seconds',
                   'n_seen_items',
                   'n_unique_items',])

dataset_macro_features.rename(columns={'session_id':'Session_Id'}, inplace=True)
dataset = dataset.merge(dataset_macro_features, on='Session_Id', how='left')
del dataset_macro_features

In [ ]:
#dataset.drop('Max_Score_TopPop15', axis=1, inplace=True)

In [ ]:
item_features=pd.read_csv("/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/original_data/item_features.csv")
subgroup_cat_feat=pd.read_csv("/content/drive/MyDrive/RS2024/Trial02/recsys2022/dataset/original_data/subgroup_cat_feat.csv")

In [ ]:
subgroup_tuples = set([tuple(x) for x in subgroup_cat_feat.values])
dataset['weight'] = 1.0
purchased_items = dataset[dataset['target'] == 1]
alpha = 0.5

# For each purchased item, check if its features match the subgroup
for index, row in purchased_items.iterrows():
    item_id = row['Item_ID']
    cat_feat = item_features[item_features['item_id'] == item_id][['feature_category_id','feature_value_id']]

    item_feature_tuples = set([tuple(x) for x in cat_feat.values])

    if item_feature_tuples & subgroup_tuples: # Check if there is at least 1 intersection between the sets, if so assign higher weight to all rows in the session
        session_id = row['Session_Id']
        dataset.loc[dataset['Session_Id'] == session_id, 'weight'] = 1+alpha

In [ ]:
def calculate_mrr(data, k=100):
    """
    Calculate MRR@k for given data.
    """
    mrr_score = 0.0
    n_sessions = data['Session_Id'].nunique()

    for session_id, group in data.groupby("Session_Id"):
        sorted_group = group.sort_values('predicted_score', ascending=False).head(k)
        sorted_group = sorted_group.reset_index(drop=True)                      # Reset index to reflect the new order
        correct_answer_index = sorted_group[sorted_group['target'] == 1].index  # Find the index (rank) of the correct answer within the sorted group
        if not correct_answer_index.empty:
            rank = correct_answer_index[0] + 1
            mrr_score += 1.0 / rank

    return mrr_score / n_sessions if n_sessions > 0 else 0

In [ ]:
from sklearn.model_selection import KFold
import lightgbm
import os

k=10
score=0
kf = KFold(n_splits=k)
mrr_score_subgroup = 0

for train_index, valid_index in kf.split(train):

    train_sessions=train["Session_Id"][train_index].tolist()
    valid_sessions=train["Session_Id"][valid_index].tolist()

    train_set=dataset[dataset["Session_Id"].isin(train_sessions)]
    valid_set=dataset[dataset["Session_Id"].isin(valid_sessions)]

    train_set=train_set.sort_values("Session_Id")
    valid_set=valid_set.sort_values("Session_Id")

    qids_train = train_set[["Session_Id"]].groupby("Session_Id")["Session_Id"].count().to_numpy()
    qids_valid = valid_set[["Session_Id"]].groupby("Session_Id")["Session_Id"].count().to_numpy()

    X_train=train_set.drop(["target","Session_Id","Item_ID"],axis=1)
    y_train=train_set["target"]
    sample_weight = train_set["weight"].values  # Extracting sample weights for the training set


    X_valid=valid_set.drop(["target","Session_Id","Item_ID"],axis=1)
    y_valid=valid_set["target"]

    model = lightgbm.LGBMRanker(
    objective="lambdarank",
    #objective="rank_xendcg",
    #metric="mrr",
    # n_estimators=2000,
    n_estimators=100,
    lambdarank_truncation_level=103,
    reg_alpha=1e-4,
    learning_rate=0.05,
    min_child_samples=400,
    subsample=0.8,
    subsample_freq=20
    )
    ranker=model.fit(
        X=X_train,
        y=y_train,
        group=qids_train,
        sample_weight=sample_weight,  # Use sample weights
        eval_set=[(X_valid, y_valid)],
        eval_group=[qids_valid],
        eval_at=(100),
        callbacks=[lightgbm.log_evaluation(),lightgbm.early_stopping(20,first_metric_only=True)],
        eval_metric=["map","ndcg"]
    )
    ranker.booster_.save_model(f'/content/drive/MyDrive/RS2024/Trial02/recsys2022/rankers/Innovation_model_{index}.txt')

    # Predict on validation set
    valid_set['predicted_score'] = ranker.predict(X_valid)
    valid_set_sorted = valid_set.sort_values(['Session_Id', 'predicted_score'], ascending=[True, False])

    # Calculate MRR@100 for all sessions
    # score+=np.max(ranker._evals_result["valid_0"]["map@100"])
    score += calculate_mrr(valid_set_sorted, k=100)

    # Calculate MRR@100 for the subgroup
    valid_set_subgroup = valid_set_sorted[valid_set_sorted['Session_Id'].isin(valid_set[valid_set['weight'] > 1.0]['Session_Id'])]

    if not valid_set_subgroup.empty:
        mrr_score_subgroup += calculate_mrr(valid_set_subgroup, k=100)

[LightGBM] [Info] Calculating query weights...
[LightGBM] [Info] Total groups: 53705, total data: 25402180
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.527713 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3318
[LightGBM] [Info] Number of data points in the train set: 25402180, number of used features: 16
[LightGBM] [Info] Total groups: 6079, total data: 2854352
[1]	valid_0's map@100: 0.190966	valid_0's ndcg@100: 0.306154
Training until validation scores don't improve for 20 rounds
[2]	valid_0's map@100: 0.221755	valid_0's ndcg@100: 0.331682
[3]	valid_0's map@100: 0.229012	valid_0's ndcg@100: 0.338128
[4]	valid_0's map@100: 0.229624	valid_0's ndcg@100: 0.338721
[5]	valid_0's map@100: 0.229505	valid_0's ndcg@100: 0.338922
[6]	valid_0's map@100: 0.231591	valid_0's ndcg@100: 0.34051
[7]	valid_0's map@100: 0.231631	valid_0's ndcg@100: 0.340778
[8]	valid_0's map@100: 0.230587	valid_0's ndcg@100: 0.339969
[9]	valid_0's map@100: 0.230692	valid_0's ndcg@100: 0.340047
[10]	valid_0's map@100: 0.231111	valid_0's ndcg@100: 0.34018
[11]	valid_0's map@100: 0.231587	valid_0's ndcg@100: 0.340494
[12]	valid_0's map@100: 0.232644	valid_0's ndcg@100: 0.341331
[13]	valid_0's map@100: 0.233305	valid_0's ndcg@100: 0.341829
[14]	valid_0's map@100: 0.232813	valid_0's ndcg@100: 0.341353
[15]	valid_0's map@100: 0.233871	valid_0's ndcg@100: 0.342183
[16]	valid_0's map@100: 0.233269	valid_0's ndcg@100: 0.341929
[17]	valid_0's map@100: 0.234077	valid_0's ndcg@100: 0.342697
[18]	valid_0's map@100: 0.233824	valid_0's ndcg@100: 0.342398
[19]	valid_0's map@100: 0.234408	valid_0's ndcg@100: 0.342958
[20]	valid_0's map@100: 0.233724	valid_0's ndcg@100: 0.342338
[21]	valid_0's map@100: 0.234286	valid_0's ndcg@100: 0.342796
[22]	valid_0's map@100: 0.234741	valid_0's ndcg@100: 0.343128
[23]	valid_0's map@100: 0.234529	valid_0's ndcg@100: 0.342939
[24]	valid_0's map@100: 0.233599	valid_0's ndcg@100: 0.342368
[25]	valid_0's map@100: 0.233798	valid_0's ndcg@100: 0.342553
[26]	valid_0's map@100: 0.233602	valid_0's ndcg@100: 0.342404
[27]	valid_0's map@100: 0.23296	valid_0's ndcg@100: 0.341914
[28]	valid_0's map@100: 0.232755	valid_0's ndcg@100: 0.341857
[29]	valid_0's map@100: 0.232963	valid_0's ndcg@100: 0.341958
[30]	valid_0's map@100: 0.233439	valid_0's ndcg@100: 0.342292
[31]	valid_0's map@100: 0.233152	valid_0's ndcg@100: 0.342131
[32]	valid_0's map@100: 0.233284	valid_0's ndcg@100: 0.342255
[33]	valid_0's map@100: 0.233804	valid_0's ndcg@100: 0.342734
[34]	valid_0's map@100: 0.234616	valid_0's ndcg@100: 0.343249
[35]	valid_0's map@100: 0.234591	valid_0's ndcg@100: 0.343302
[36]	valid_0's map@100: 0.234839	valid_0's ndcg@100: 0.343491
[37]	valid_0's map@100: 0.23516	valid_0's ndcg@100: 0.343757
[38]	valid_0's map@100: 0.235178	valid_0's ndcg@100: 0.3437
[39]	valid_0's map@100: 0.234676	valid_0's ndcg@100: 0.343306
[40]	valid_0's map@100: 0.234905	valid_0's ndcg@100: 0.343486
[41]	valid_0's map@100: 0.234704	valid_0's ndcg@100: 0.343449
[42]	valid_0's map@100: 0.23454	valid_0's ndcg@100: 0.343342
[43]	valid_0's map@100: 0.234216	valid_0's ndcg@100: 0.343111
[44]	valid_0's map@100: 0.234416	valid_0's ndcg@100: 0.343341
[45]	valid_0's map@100: 0.234513	valid_0's ndcg@100: 0.343428
[46]	valid_0's map@100: 0.23459	valid_0's ndcg@100: 0.343551
[47]	valid_0's map@100: 0.234547	valid_0's ndcg@100: 0.343468
[48]	valid_0's map@100: 0.234531	valid_0's ndcg@100: 0.343498
[49]	valid_0's map@100: 0.234832	valid_0's ndcg@100: 0.343706
[50]	valid_0's map@100: 0.234863	valid_0's ndcg@100: 0.343805
[51]	valid_0's map@100: 0.23501	valid_0's ndcg@100: 0.343824
[52]	valid_0's map@100: 0.234602	valid_0's ndcg@100: 0.343474
[53]	valid_0's map@100: 0.234701	valid_0's ndcg@100: 0.343578
[54]	valid_0's map@100: 0.234428	valid_0's ndcg@100: 0.343348
[55]	valid_0's map@100: 0.234622	valid_0's ndcg@100: 0.343543
[56]	valid_0's map@100: 0.234644	valid_0's ndcg@100: 0.343581
[57]	valid_0's map@100: 0.234444	valid_0's ndcg@100: 0.343395
[58]	valid_0's map@100: 0.234663	valid_0's ndcg@100: 0.343575
Early stopping, best iteration is:
[38]	valid_0's map@100: 0.235178	valid_0's ndcg@100: 0.3437
Evaluated only: map@100
[LightGBM] [Info] Calculating query weights...
[LightGBM] [Info] Total groups: 53747, total data: 25422326
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.591968 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3315
[LightGBM] [Info] Number of data points in the train set: 25422326, number of used features: 16
[LightGBM] [Info] Total groups: 6037, total data: 2834206
[1]	valid_0's map@100: 0.20377	valid_0's ndcg@100: 0.31937
Training until validation scores don't improve for 20 rounds
[2]	valid_0's map@100: 0.234106	valid_0's ndcg@100: 0.343826
[3]	valid_0's map@100: 0.242338	valid_0's ndcg@100: 0.350251
[4]	valid_0's map@100: 0.243798	valid_0's ndcg@100: 0.351848
[5]	valid_0's map@100: 0.244559	valid_0's ndcg@100: 0.352053
[6]	valid_0's map@100: 0.245075	valid_0's ndcg@100: 0.3527
[7]	valid_0's map@100: 0.245783	valid_0's ndcg@100: 0.353064
[8]	valid_0's map@100: 0.245674	valid_0's ndcg@100: 0.353047
[9]	valid_0's map@100: 0.246426	valid_0's ndcg@100: 0.353624
[10]	valid_0's map@100: 0.246696	valid_0's ndcg@100: 0.353879
[11]	valid_0's map@100: 0.247213	valid_0's ndcg@100: 0.354259
[12]	valid_0's map@100: 0.246829	valid_0's ndcg@100: 0.353928
[13]	valid_0's map@100: 0.2463	valid_0's ndcg@100: 0.353455
[14]	valid_0's map@100: 0.246941	valid_0's ndcg@100: 0.353985
[15]	valid_0's map@100: 0.246736	valid_0's ndcg@100: 0.353826
[16]	valid_0's map@100: 0.246781	valid_0's ndcg@100: 0.353813
[17]	valid_0's map@100: 0.247356	valid_0's ndcg@100: 0.354136
[18]	valid_0's map@100: 0.247396	valid_0's ndcg@100: 0.354252
[19]	valid_0's map@100: 0.247498	valid_0's ndcg@100: 0.354442
[20]	valid_0's map@100: 0.247867	valid_0's ndcg@100: 0.35483
[21]	valid_0's map@100: 0.24845	valid_0's ndcg@100: 0.355243
[22]	valid_0's map@100: 0.248589	valid_0's ndcg@100: 0.355261
[23]	valid_0's map@100: 0.248427	valid_0's ndcg@100: 0.355127
[24]	valid_0's map@100: 0.248075	valid_0's ndcg@100: 0.354768
[25]	valid_0's map@100: 0.248705	valid_0's ndcg@100: 0.355457
[26]	valid_0's map@100: 0.248416	valid_0's ndcg@100: 0.355349
[27]	valid_0's map@100: 0.248381	valid_0's ndcg@100: 0.355215
[28]	valid_0's map@100: 0.248591	valid_0's ndcg@100: 0.355482
[29]	valid_0's map@100: 0.248257	valid_0's ndcg@100: 0.355235
[30]	valid_0's map@100: 0.248541	valid_0's ndcg@100: 0.355626
[31]	valid_0's map@100: 0.248212	valid_0's ndcg@100: 0.355441
[32]	valid_0's map@100: 0.247868	valid_0's ndcg@100: 0.355269
[33]	valid_0's map@100: 0.248002	valid_0's ndcg@100: 0.355324
[34]	valid_0's map@100: 0.248433	valid_0's ndcg@100: 0.35561
[35]	valid_0's map@100: 0.247943	valid_0's ndcg@100: 0.355186
[36]	valid_0's map@100: 0.248274	valid_0's ndcg@100: 0.355544
[37]	valid_0's map@100: 0.248558	valid_0's ndcg@100: 0.355735
[38]	valid_0's map@100: 0.248966	valid_0's ndcg@100: 0.356067
[39]	valid_0's map@100: 0.248837	valid_0's ndcg@100: 0.356013
[40]	valid_0's map@100: 0.248437	valid_0's ndcg@100: 0.355766
[41]	valid_0's map@100: 0.248353	valid_0's ndcg@100: 0.35576
[42]	valid_0's map@100: 0.248391	valid_0's ndcg@100: 0.355759
[43]	valid_0's map@100: 0.248939	valid_0's ndcg@100: 0.356091
[44]	valid_0's map@100: 0.249087	valid_0's ndcg@100: 0.356177
[45]	valid_0's map@100: 0.249007	valid_0's ndcg@100: 0.356146
[46]	valid_0's map@100: 0.249005	valid_0's ndcg@100: 0.356249
[47]	valid_0's map@100: 0.249149	valid_0's ndcg@100: 0.356359
[48]	valid_0's map@100: 0.249456	valid_0's ndcg@100: 0.35657
[49]	valid_0's map@100: 0.249273	valid_0's ndcg@100: 0.356536
[50]	valid_0's map@100: 0.248886	valid_0's ndcg@100: 0.356109
[51]	valid_0's map@100: 0.249007	valid_0's ndcg@100: 0.356255
[52]	valid_0's map@100: 0.248743	valid_0's ndcg@100: 0.356069
[53]	valid_0's map@100: 0.248939	valid_0's ndcg@100: 0.356253
[54]	valid_0's map@100: 0.248848	valid_0's ndcg@100: 0.356155
[55]	valid_0's map@100: 0.249375	valid_0's ndcg@100: 0.356523
[56]	valid_0's map@100: 0.248977	valid_0's ndcg@100: 0.356238
[57]	valid_0's map@100: 0.249491	valid_0's ndcg@100: 0.356665
[58]	valid_0's map@100: 0.249536	valid_0's ndcg@100: 0.356818
[59]	valid_0's map@100: 0.249591	valid_0's ndcg@100: 0.356835
[60]	valid_0's map@100: 0.249639	valid_0's ndcg@100: 0.356839
[61]	valid_0's map@100: 0.24942	valid_0's ndcg@100: 0.356701
[62]	valid_0's map@100: 0.249806	valid_0's ndcg@100: 0.356923
[63]	valid_0's map@100: 0.249679	valid_0's ndcg@100: 0.356802
[64]	valid_0's map@100: 0.249394	valid_0's ndcg@100: 0.356507
[65]	valid_0's map@100: 0.249132	valid_0's ndcg@100: 0.356357
[66]	valid_0's map@100: 0.249483	valid_0's ndcg@100: 0.356597
[67]	valid_0's map@100: 0.249322	valid_0's ndcg@100: 0.35653
[68]	valid_0's map@100: 0.249522	valid_0's ndcg@100: 0.356824
[69]	valid_0's map@100: 0.249941	valid_0's ndcg@100: 0.357212
[70]	valid_0's map@100: 0.249783	valid_0's ndcg@100: 0.35704
[71]	valid_0's map@100: 0.249986	valid_0's ndcg@100: 0.357226
[72]	valid_0's map@100: 0.250098	valid_0's ndcg@100: 0.357365
[73]	valid_0's map@100: 0.249884	valid_0's ndcg@100: 0.357344
[74]	valid_0's map@100: 0.250016	valid_0's ndcg@100: 0.357402
[75]	valid_0's map@100: 0.24959	valid_0's ndcg@100: 0.35706
[76]	valid_0's map@100: 0.249712	valid_0's ndcg@100: 0.357158
[77]	valid_0's map@100: 0.249639	valid_0's ndcg@100: 0.357061
[78]	valid_0's map@100: 0.249625	valid_0's ndcg@100: 0.357056
[79]	valid_0's map@100: 0.249556	valid_0's ndcg@100: 0.357002
[80]	valid_0's map@100: 0.249669	valid_0's ndcg@100: 0.357029
[81]	valid_0's map@100: 0.249561	valid_0's ndcg@100: 0.356984
[82]	valid_0's map@100: 0.249305	valid_0's ndcg@100: 0.356777
[83]	valid_0's map@100: 0.249338	valid_0's ndcg@100: 0.356787
[84]	valid_0's map@100: 0.249538	valid_0's ndcg@100: 0.356965
[85]	valid_0's map@100: 0.249437	valid_0's ndcg@100: 0.356864
[86]	valid_0's map@100: 0.249523	valid_0's ndcg@100: 0.356903
[87]	valid_0's map@100: 0.249669	valid_0's ndcg@100: 0.357023
[88]	valid_0's map@100: 0.249462	valid_0's ndcg@100: 0.35683
[89]	valid_0's map@100: 0.250215	valid_0's ndcg@100: 0.357386
[90]	valid_0's map@100: 0.25015	valid_0's ndcg@100: 0.357384
[91]	valid_0's map@100: 0.250341	valid_0's ndcg@100: 0.357581
[92]	valid_0's map@100: 0.25058	valid_0's ndcg@100: 0.357767
[93]	valid_0's map@100: 0.250486	valid_0's ndcg@100: 0.357678
[94]	valid_0's map@100: 0.250487	valid_0's ndcg@100: 0.357702
[95]	valid_0's map@100: 0.250478	valid_0's ndcg@100: 0.357668
[96]	valid_0's map@100: 0.250619	valid_0's ndcg@100: 0.357851
[97]	valid_0's map@100: 0.250655	valid_0's ndcg@100: 0.357803
[98]	valid_0's map@100: 0.250435	valid_0's ndcg@100: 0.357577
[99]	valid_0's map@100: 0.250443	valid_0's ndcg@100: 0.357544
[100]	valid_0's map@100: 0.250689	valid_0's ndcg@100: 0.357708
Did not meet early stopping. Best iteration is:
[100]	valid_0's map@100: 0.250689	valid_0's ndcg@100: 0.357708
Evaluated only: map@100
[LightGBM] [Info] Calculating query weights...
[LightGBM] [Info] Total groups: 53856, total data: 25439823
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.650093 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3314
[LightGBM] [Info] Number of data points in the train set: 25439823, number of used features: 16
[LightGBM] [Info] Total groups: 5928, total data: 2816709
[1]	valid_0's map@100: 0.142308	valid_0's ndcg@100: 0.263061
Training until validation scores don't improve for 20 rounds
[2]	valid_0's map@100: 0.213445	valid_0's ndcg@100: 0.319946
[3]	valid_0's map@100: 0.220101	valid_0's ndcg@100: 0.326115
[4]	valid_0's map@100: 0.222444	valid_0's ndcg@100: 0.328431
[5]	valid_0's map@100: 0.223454	valid_0's ndcg@100: 0.329174
[6]	valid_0's map@100: 0.224936	valid_0's ndcg@100: 0.330644
[7]	valid_0's map@100: 0.224214	valid_0's ndcg@100: 0.329821
[8]	valid_0's map@100: 0.224581	valid_0's ndcg@100: 0.33023
[9]	valid_0's map@100: 0.223885	valid_0's ndcg@100: 0.329794
[10]	valid_0's map@100: 0.223602	valid_0's ndcg@100: 0.329568
[11]	valid_0's map@100: 0.224397	valid_0's ndcg@100: 0.330345
[12]	valid_0's map@100: 0.224806	valid_0's ndcg@100: 0.330603
[13]	valid_0's map@100: 0.224768	valid_0's ndcg@100: 0.330499
[14]	valid_0's map@100: 0.224791	valid_0's ndcg@100: 0.330447
[15]	valid_0's map@100: 0.224734	valid_0's ndcg@100: 0.33038
[16]	valid_0's map@100: 0.224612	valid_0's ndcg@100: 0.330433
[17]	valid_0's map@100: 0.224318	valid_0's ndcg@100: 0.330297
[18]	valid_0's map@100: 0.225149	valid_0's ndcg@100: 0.330998
[19]	valid_0's map@100: 0.225298	valid_0's ndcg@100: 0.331064
[20]	valid_0's map@100: 0.225275	valid_0's ndcg@100: 0.330838
[21]	valid_0's map@100: 0.225381	valid_0's ndcg@100: 0.331139
[22]	valid_0's map@100: 0.225501	valid_0's ndcg@100: 0.331276
[23]	valid_0's map@100: 0.225762	valid_0's ndcg@100: 0.331637
[24]	valid_0's map@100: 0.226225	valid_0's ndcg@100: 0.33201
[25]	valid_0's map@100: 0.226368	valid_0's ndcg@100: 0.332153
[26]	valid_0's map@100: 0.225265	valid_0's ndcg@100: 0.331348
[27]	valid_0's map@100: 0.225809	valid_0's ndcg@100: 0.331796
[28]	valid_0's map@100: 0.225853	valid_0's ndcg@100: 0.331724
[29]	valid_0's map@100: 0.225798	valid_0's ndcg@100: 0.331725
[30]	valid_0's map@100: 0.226007	valid_0's ndcg@100: 0.331733
[31]	valid_0's map@100: 0.225473	valid_0's ndcg@100: 0.331511
[32]	valid_0's map@100: 0.225649	valid_0's ndcg@100: 0.331516
[33]	valid_0's map@100: 0.225798	valid_0's ndcg@100: 0.331683
[34]	valid_0's map@100: 0.225355	valid_0's ndcg@100: 0.331289
[35]	valid_0's map@100: 0.225805	valid_0's ndcg@100: 0.331707
[36]	valid_0's map@100: 0.226123	valid_0's ndcg@100: 0.332053
[37]	valid_0's map@100: 0.225889	valid_0's ndcg@100: 0.331869
[38]	valid_0's map@100: 0.22588	valid_0's ndcg@100: 0.331866
[39]	valid_0's map@100: 0.226002	valid_0's ndcg@100: 0.331997
[40]	valid_0's map@100: 0.225762	valid_0's ndcg@100: 0.331731
[41]	valid_0's map@100: 0.225978	valid_0's ndcg@100: 0.331936
[42]	valid_0's map@100: 0.226141	valid_0's ndcg@100: 0.33212
[43]	valid_0's map@100: 0.226061	valid_0's ndcg@100: 0.332213
[44]	valid_0's map@100: 0.226105	valid_0's ndcg@100: 0.332176
[45]	valid_0's map@100: 0.226455	valid_0's ndcg@100: 0.332426
[46]	valid_0's map@100: 0.226434	valid_0's ndcg@100: 0.332397
[47]	valid_0's map@100: 0.226327	valid_0's ndcg@100: 0.332359
[48]	valid_0's map@100: 0.226818	valid_0's ndcg@100: 0.332797
[49]	valid_0's map@100: 0.226901	valid_0's ndcg@100: 0.332881
[50]	valid_0's map@100: 0.226743	valid_0's ndcg@100: 0.332682
[51]	valid_0's map@100: 0.226687	valid_0's ndcg@100: 0.332624
[52]	valid_0's map@100: 0.226503	valid_0's ndcg@100: 0.332528
[53]	valid_0's map@100: 0.226816	valid_0's ndcg@100: 0.332766
[54]	valid_0's map@100: 0.226788	valid_0's ndcg@100: 0.332769
[55]	valid_0's map@100: 0.226647	valid_0's ndcg@100: 0.332713
[56]	valid_0's map@100: 0.226615	valid_0's ndcg@100: 0.332678
[57]	valid_0's map@100: 0.226736	valid_0's ndcg@100: 0.332837
[58]	valid_0's map@100: 0.226815	valid_0's ndcg@100: 0.332786
[59]	valid_0's map@100: 0.226589	valid_0's ndcg@100: 0.33266
[60]	valid_0's map@100: 0.22642	valid_0's ndcg@100: 0.332595
[61]	valid_0's map@100: 0.226228	valid_0's ndcg@100: 0.332482
[62]	valid_0's map@100: 0.226175	valid_0's ndcg@100: 0.332412
[63]	valid_0's map@100: 0.226288	valid_0's ndcg@100: 0.33244
[64]	valid_0's map@100: 0.225759	valid_0's ndcg@100: 0.332066
[65]	valid_0's map@100: 0.225565	valid_0's ndcg@100: 0.331882
[66]	valid_0's map@100: 0.225539	valid_0's ndcg@100: 0.331888
[67]	valid_0's map@100: 0.225534	valid_0's ndcg@100: 0.331891
[68]	valid_0's map@100: 0.22561	valid_0's ndcg@100: 0.332024
[69]	valid_0's map@100: 0.225636	valid_0's ndcg@100: 0.332014
Early stopping, best iteration is:
[49]	valid_0's map@100: 0.226901	valid_0's ndcg@100: 0.332881
Evaluated only: map@100
[LightGBM] [Info] Calculating query weights...
[LightGBM] [Info] Total groups: 53767, total data: 25385645
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.957637 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3312
[LightGBM] [Info] Number of data points in the train set: 25385645, number of used features: 16
[LightGBM] [Info] Total groups: 6017, total data: 2870887
[1]	valid_0's map@100: 0.154387	valid_0's ndcg@100: 0.278525
Training until validation scores don't improve for 20 rounds
[2]	valid_0's map@100: 0.247854	valid_0's ndcg@100: 0.353656
[3]	valid_0's map@100: 0.254634	valid_0's ndcg@100: 0.359489
[4]	valid_0's map@100: 0.258844	valid_0's ndcg@100: 0.3627
[5]	valid_0's map@100: 0.260242	valid_0's ndcg@100: 0.363984
[6]	valid_0's map@100: 0.26109	valid_0's ndcg@100: 0.364842
[7]	valid_0's map@100: 0.2612	valid_0's ndcg@100: 0.364987
[8]	valid_0's map@100: 0.261455	valid_0's ndcg@100: 0.36516
[9]	valid_0's map@100: 0.262007	valid_0's ndcg@100: 0.365557
[10]	valid_0's map@100: 0.263346	valid_0's ndcg@100: 0.366604
[11]	valid_0's map@100: 0.263215	valid_0's ndcg@100: 0.366781
[12]	valid_0's map@100: 0.263553	valid_0's ndcg@100: 0.366809
[13]	valid_0's map@100: 0.262398	valid_0's ndcg@100: 0.366026
[14]	valid_0's map@100: 0.262162	valid_0's ndcg@100: 0.365789
[15]	valid_0's map@100: 0.262499	valid_0's ndcg@100: 0.366028
[16]	valid_0's map@100: 0.262711	valid_0's ndcg@100: 0.366346
[17]	valid_0's map@100: 0.262273	valid_0's ndcg@100: 0.36599
[18]	valid_0's map@100: 0.263186	valid_0's ndcg@100: 0.366585
[19]	valid_0's map@100: 0.263238	valid_0's ndcg@100: 0.366727
[20]	valid_0's map@100: 0.263699	valid_0's ndcg@100: 0.367243
[21]	valid_0's map@100: 0.263502	valid_0's ndcg@100: 0.367013
[22]	valid_0's map@100: 0.263554	valid_0's ndcg@100: 0.367188
[23]	valid_0's map@100: 0.264013	valid_0's ndcg@100: 0.367393
[24]	valid_0's map@100: 0.264798	valid_0's ndcg@100: 0.368052
[25]	valid_0's map@100: 0.2641	valid_0's ndcg@100: 0.367623
[26]	valid_0's map@100: 0.263343	valid_0's ndcg@100: 0.366943
[27]	valid_0's map@100: 0.263937	valid_0's ndcg@100: 0.36738
[28]	valid_0's map@100: 0.263858	valid_0's ndcg@100: 0.367362
[29]	valid_0's map@100: 0.264045	valid_0's ndcg@100: 0.367525
[30]	valid_0's map@100: 0.263597	valid_0's ndcg@100: 0.367017
[31]	valid_0's map@100: 0.263452	valid_0's ndcg@100: 0.36696
[32]	valid_0's map@100: 0.263129	valid_0's ndcg@100: 0.366742
[33]	valid_0's map@100: 0.264345	valid_0's ndcg@100: 0.367611
[34]	valid_0's map@100: 0.264407	valid_0's ndcg@100: 0.367651
[35]	valid_0's map@100: 0.263748	valid_0's ndcg@100: 0.36727
[36]	valid_0's map@100: 0.263903	valid_0's ndcg@100: 0.367381
[37]	valid_0's map@100: 0.263784	valid_0's ndcg@100: 0.367455
[38]	valid_0's map@100: 0.264	valid_0's ndcg@100: 0.367658
[39]	valid_0's map@100: 0.26407	valid_0's ndcg@100: 0.367661
[40]	valid_0's map@100: 0.264196	valid_0's ndcg@100: 0.367889
[41]	valid_0's map@100: 0.264137	valid_0's ndcg@100: 0.3679
[42]	valid_0's map@100: 0.264317	valid_0's ndcg@100: 0.367976
[43]	valid_0's map@100: 0.264614	valid_0's ndcg@100: 0.368235
[44]	valid_0's map@100: 0.264467	valid_0's ndcg@100: 0.368075
Early stopping, best iteration is:
[24]	valid_0's map@100: 0.264798	valid_0's ndcg@100: 0.368052
Evaluated only: map@100
[LightGBM] [Info] Calculating query weights...
[LightGBM] [Info] Total groups: 53869, total data: 25438326
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.996103 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3315
[LightGBM] [Info] Number of data points in the train set: 25438326, number of used features: 16

In [ ]:
final_performance = score / k
final_performance_subgroup = mrr_score_subgroup / k
print("Overall MRR@100 with label in candidates = ", final_performance)
print("Subgroup MRR@100 with label in candidates = ", final_performance_subgroup)

Overall MRR@100 with label in candidates =  0.2550750856206885
Subgroup MRR@100 with label in candidates =  0.29816309968649324

In [ ]:
print("Normalized score Overall MRR@100 ", final_performance*HITRATE)
print("Normalized score Subgroup MRR@100 ", final_performance_subgroup*HITRATE)

Normalized score Overall MRR@100  0.18688001125915735
Normalized score Subgroup MRR@100  0.21844831803501608